# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170616_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='grplist',
            field=models.ManyToManyField(null=True, to='timetable.Groups'),
        ),
    ]
