# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170617_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='grplist',
            field=models.ManyToManyField(to='timetable.Groups'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='subj_list',
            field=models.ManyToManyField(to='timetable.Subjects'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='sublist',
            field=models.ManyToManyField(to='timetable.Subjects'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='faclist',
            field=models.ManyToManyField(to='timetable.Faculty'),
        ),
    ]
