# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20170617_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='hours',
        ),
        migrations.AddField(
            model_name='subjects',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subtype',
            field=models.CharField(default='Normal', max_length=20),
            preserve_default=False,
        ),
    ]
