# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20170621_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='constr1list',
        ),
        migrations.AddField(
            model_name='subjects',
            name='slots',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subjects',
            name='whpd',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timetable.Whpd'),
            preserve_default=False,
        ),
    ]
