# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20170621_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='whpd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Whpd'),
        ),
    ]
