# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20170621_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='whpd',
        ),
        migrations.AddField(
            model_name='subjects',
            name='constr1list',
            field=models.ManyToManyField(to='timetable.Whpd'),
        ),
    ]
