# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20170621_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='constr1list',
        ),
        migrations.AddField(
            model_name='subjects',
            name='whpd',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subjects',
            name='whpd_check',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WHPD',
        ),
    ]
