# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_auto_20170621_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
